#!/usr/bin/env python3
"""
Rebuild app/res/drawable/ic_launcher_foreground.xml from the DeepSeek app's own
launcher icon, so the whale path is byte-identical instead of hand-copied.

Source: base.apk pulled from the phone.
  res/PF.xml  -> drawable/ic_launcher_foreground (vector, whale path)
  res/9s.xml  -> the gradient used as the whale's fillColor

The original vector points fillColor at a separate gradient resource. That works
inside its own APK but not in ours, so the gradient is inlined via <aapt:attr>,
which is the same mechanism the original uses.

tmp_icon/base.apk is not kept in the project (22 MB). If it is missing, this
script pulls the DeepSeek app off the connected phone and re-creates it.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
AAPT2 = os.path.join(ROOT, "tools", "build-tools", "aapt2.exe")
ADB = os.path.join(ROOT, "tools", "platform-tools", "adb.exe")
APK = os.path.join(ROOT, "tmp_icon", "base.apk")
OUT = os.path.join(ROOT, "app", "res", "drawable", "ic_launcher_foreground.xml")
PACKAGE = "com.deepseek.chat"


def ensure_apk():
    """Pull the source APK off the phone when it is not already on disk."""
    if os.path.isfile(APK):
        return
    if not os.path.isfile(ADB):
        raise SystemExit("missing %s and no adb at %s to pull it with" % (APK, ADB))

    print("tmp_icon/base.apk not present; pulling %s from the phone..." % PACKAGE)
    listing = subprocess.run(
        [ADB, "shell", "pm", "path", PACKAGE],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    remote = [line.strip()[len("package:"):]
              for line in listing.stdout.splitlines()
              if line.strip().startswith("package:")]
    if not remote:
        raise SystemExit(
            "%s is not installed on the connected phone, so the icon cannot be extracted."
            % PACKAGE)

    os.makedirs(os.path.dirname(APK), exist_ok=True)
    pull = subprocess.run(
        [ADB, "pull", remote[0], APK],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    if pull.returncode != 0 or not os.path.isfile(APK):
        raise SystemExit("adb pull failed:\n%s" % (pull.stdout + pull.stderr))
    print("  pulled %.1f MB" % (os.path.getsize(APK) / 1024.0 / 1024.0))


def xmltree(path_in_apk):
    result = subprocess.run(
        [AAPT2, "dump", "xmltree", APK, "--file", path_in_apk],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        raise SystemExit("aapt2 failed on %s:\n%s" % (path_in_apk, result.stderr))
    return result.stdout


def one(pattern, text, label):
    match = re.search(pattern, text)
    if not match:
        raise SystemExit("could not find %s" % label)
    return match.group(1)


def main():
    ensure_apk()
    fg = xmltree("res/PF.xml")

    path_data = one(r'pathData\(0x01010405\)="([^"]*)"', fg, "pathData")
    scale_x = one(r'scaleX\(0x01010324\)=([\d.]+)', fg, "scaleX")
    scale_y = one(r'scaleY\(0x01010325\)=([\d.]+)', fg, "scaleY")
    trans_x = one(r'translateX\(0x0101045a\)=([\d.]+)', fg, "translateX")
    trans_y = one(r'translateY\(0x0101045b\)=([\d.]+)', fg, "translateY")
    vp_w = one(r'viewportWidth\(0x01010402\)=([\d.]+)', fg, "viewportWidth")
    vp_h = one(r'viewportHeight\(0x01010403\)=([\d.]+)', fg, "viewportHeight")

    grad = xmltree("res/9s.xml")
    colors = re.findall(r'color\(0x010101a5\)=(#[0-9a-fA-F]+)', grad)
    offsets = re.findall(r'offset\(0x01010514\)=([\d.eE+-]+)', grad)
    start_x = one(r'startX\(0x01010510\)=([\d.]+)', grad, "startX")
    start_y = one(r'startY\(0x01010511\)=([\d.]+)', grad, "startY")
    end_x = one(r'endX\(0x01010512\)=([\d.]+)', grad, "endX")
    end_y = one(r'endY\(0x01010513\)=([\d.]+)', grad, "endY")

    if len(colors) != len(offsets):
        raise SystemExit("gradient colour/offset count mismatch")

    stops = "\n".join(
        '                    <item android:color="%s" android:offset="%s" />'
        % (c, "%g" % float(o))
        for c, o in zip(colors, offsets))

    xml = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by extract_icon.py from the installed DeepSeek app (com.deepseek.chat).
     Do not hand-edit: re-run the script instead. Personal use only. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="%(vpw)s"
    android:viewportHeight="%(vph)s">

    <group
        android:scaleX="%(sx)s"
        android:scaleY="%(sy)s"
        android:translateX="%(tx)s"
        android:translateY="%(ty)s">

        <path android:pathData="%(path)s">
            <aapt:attr name="android:fillColor">
                <gradient
                    android:type="linear"
                    android:startX="%(gsx)s"
                    android:startY="%(gsy)s"
                    android:endX="%(gex)s"
                    android:endY="%(gey)s">
%(stops)s
                </gradient>
            </aapt:attr>
        </path>
    </group>
</vector>
''' % {
        "vpw": vp_w, "vph": vp_h,
        "sx": scale_x, "sy": scale_y, "tx": trans_x, "ty": trans_y,
        "path": path_data,
        "gsx": start_x, "gsy": start_y, "gex": end_x, "gey": end_y,
        "stops": stops,
    }

    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(xml)

    print("wrote %s" % OUT)
    print("  viewport    %s x %s" % (vp_w, vp_h))
    print("  transform   scale(%s, %s) translate(%s, %s)" % (scale_x, scale_y, trans_x, trans_y))
    print("  gradient    %s -> %s, stops=%s" % (colors[0], colors[-1], len(colors)))
    print("  path data   %d characters" % len(path_data))


if __name__ == "__main__":
    main()
